# Generated by Django 5.1 on 2024-08-31 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='org_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.IntegerField()),
                ('contact_code', models.IntegerField()),
                ('contact_person', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('active_date', models.DateTimeField()),
                ('inactive_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='org_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.IntegerField()),
                ('short_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=60)),
                ('local_currency_code', models.CharField(max_length=3)),
                ('reporting_currency_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='org_contact_phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_line_1', models.CharField(max_length=20)),
                ('land_line_2', models.CharField(max_length=20)),
                ('mobile_1', models.CharField(max_length=20)),
                ('mobile_2', models.CharField(max_length=20)),
                ('personal_email', models.CharField(max_length=30)),
                ('contact_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.org_contacts')),
            ],
        ),
        migrations.CreateModel(
            name='org_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.IntegerField()),
                ('short_name', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=60)),
                ('local_currency_code', models.CharField(max_length=3)),
                ('reporting_currency_code', models.CharField(max_length=3)),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.org_profile')),
            ],
        ),
        migrations.AddField(
            model_name='org_contacts',
            name='org_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.org_profile'),
        ),
        migrations.CreateModel(
            name='org_applicable_taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.IntegerField()),
                ('tax_number', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('territory_tax_code', models.CharField(max_length=30)),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.org_profile')),
            ],
        ),
        migrations.CreateModel(
            name='org_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_code', models.IntegerField()),
                ('address_line', models.CharField(max_length=300)),
                ('city_code', models.CharField(max_length=10)),
                ('address_type', models.CharField(max_length=30)),
                ('active_date', models.DateTimeField()),
                ('inactive_date', models.DateTimeField()),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.org_profile')),
            ],
        ),
    ]
